/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUI.java
 *
 * Created on 30/04/2012, 11:36:46
 */
package Teste;

import diagram.Grafo;
import diagram.editor.EditorAplicativoGrafo;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author ANDRE
 */
public class GUI extends JFrame {
    private Grafo grafo;
    private EditorAplicativoGrafo editor;
    private FrameContainer container;
    private Menu menu;

    /** Creates new form GUI */
    public GUI() {
        initComponents();
        Menu m = new Menu(JMenuBar,this);
        menu = m;
        this.setTitle("EDITOR DE DIAGRAMAS (GED)");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        Abas = new javax.swing.JTabbedPane();
        JMenuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Abas.setAutoscrolls(true);
        setJMenuBar(JMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Abas, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Abas, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    public int AdicionarAbas(){
        String nomeProjeto = this.getNomeProjeto();
        
        if(nomeProjeto!=null)
        {
            grafo = new Grafo();
            
            editor = new EditorAplicativoGrafo(grafo,this);
            
            grafo.setEditor(editor);
                    
            container = new FrameContainer(editor);
            container.setLayout(new BorderLayout());
                
            //Adiciona o JScrollPane ao Painel
            container.add(BorderLayout.CENTER,editor);
                    
            //Adicionar o painel a JTabbedPane() na Tabela
            Abas.addTab(nomeProjeto, container);


            //Ir para a aba selecionada
            Abas.setSelectedComponent(container);

            repaint();
            
            //A aba foi adicionada com sucesso
            return 1;
        }
        
        //A aba não foi adicionada
        return 0;
                
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Abas;
    private javax.swing.JMenuBar JMenuBar;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables


    public EditorAplicativoGrafo getEditorSelecionado()
    {
        if(Abas.getComponentCount()!=0)
        {
            FrameContainer containerTemp = (FrameContainer)Abas.getSelectedComponent();
            EditorAplicativoGrafo editorgrafo = containerTemp.getEditor();
            return editorgrafo;
        }
        return null;
    }

    public int getQuantidadeAbas()
    {
        return Abas.getTabCount();
    }

    void RemoverAbas(FrameContainer containerTemp) {
        Abas.remove(containerTemp);
    }

       //Recebe o nome do projeto
    public String getNomeProjeto() 
    {
        String nome=""; 
        while ("".equals(nome)) 
        {
            //Recebe o nome digitado na variável nome
            nome = JOptionPane.showInputDialog(editor,"Digite o nome do projeto?","Digite o nome do projeto?",1);

            //Se não foi digitado nenhum nome, pede para digitar um nome válido
            if ("".equals(nome))  
            {
                JOptionPane.showMessageDialog(editor, "Nome do projeto Inválido");
            }
        }
                    
        //Se não foi clicado em cancelar, cria o projeto com o nome digitado
        if (nome!=null)
        {
            return nome;
        }
        return null;
    }
}
